# Generated by Django 4.2.3 on 2023-08-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empcomp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_identifier",
                    models.IntegerField(
                        blank=True, db_column="Employee Identifier", null=True
                    ),
                ),
                (
                    "salaries",
                    models.FloatField(blank=True, db_column="Salaries", null=True),
                ),
                (
                    "other_salaries",
                    models.FloatField(
                        blank=True, db_column="Other Salaries", null=True
                    ),
                ),
                (
                    "total_salary",
                    models.FloatField(blank=True, db_column="Total Salary", null=True),
                ),
                (
                    "retirement",
                    models.FloatField(blank=True, db_column="Retirement", null=True),
                ),
                (
                    "health_and_dental",
                    models.FloatField(
                        blank=True, db_column="Health and Dental", null=True
                    ),
                ),
                (
                    "other_benefits",
                    models.FloatField(
                        blank=True, db_column="Other Benefits", null=True
                    ),
                ),
                (
                    "total_benefits",
                    models.FloatField(
                        blank=True, db_column="Total Benefits", null=True
                    ),
                ),
                (
                    "total_compensation",
                    models.FloatField(
                        blank=True, db_column="Total Compensation", null=True
                    ),
                ),
            ],
            options={
                "db_table": "employee-compensation",
                "managed": False,
            },
        ),
    ]
